add openstack-dep charts
kungze/charts pull request #12
Opened 2022-02-23 01:41 UTC by fightdou

2022-02-24 00:56 UTC, jeffyjf requested changes
还应当生成一个 configmap，保存各个服务的域名，后面写 openstack 各个服务的时候就可以从这个 configmap 中读取域名，不用在手动填写了

2022-02-24 00:56 UTC, jeffyjf commented on charts/openstack-dep/values.yaml
> +externalDatabase:
这个应当不需要了，如果需要的话也应当是在部署 openstack 具体服务的时候在写这个

2022-02-24 00:56 UTC, jeffyjf commented on charts/openstack-dep/values.schema.json
> +                    "title": "Use a new MariaDB database hosted in the cluster",
我觉得应当在 values.yaml 的注释中加上 [t#<标题>] 不然这里的 title 太长，渲染出来的表单应该很不好看

2022-03-01 01:23 UTC, jeffyjf requested changes

2022-03-01 01:23 UTC, jeffyjf commented on charts/openstack-dep/Chart.yaml
> +  - name: Openstack
这儿改为 kungze

2022-03-01 01:23 UTC, jeffyjf commented on charts/openstack-dep/Chart.yaml
> +      - bitnami-common
common 为什么要用 tag 呢，我的理解是 tag 是控制依赖的开关的，common 不是应该一直存在的吗

2022-03-01 01:23 UTC, jeffyjf commented on charts/openstack-dep/values.schema.json
> +		            "title": "自动生成密钥名称",
缩进不对，标题感觉意思不对，叫 “secret 名称”  我觉得更标准一些

2022-03-01 01:23 UTC, jeffyjf commented on charts/openstack-dep/values.schema.json
> +                    "description": "MariaDB architecture. Allowed values: `standalone` or `replication`",
这儿是不是也应该加一个 hidden

2022-03-01 01:23 UTC, jeffyjf commented on charts/openstack-dep/values.schema.json
> +                    "title": "开启mariadb",
所有的开启改为 “部署” 含义应该会更符合一些，然后就是汉字和字母之间最好有一个空格

2022-03-01 02:14 UTC, fightdou commented on charts/openstack-dep/Chart.yaml
> +      - bitnami-common
控制依赖开关是condition这个关键字，给common加tag应该是怕跟别的charts名称冲突

2022-03-01 02:50 UTC, fightdou commented on charts/openstack-dep/values.schema.json
> +                    "title": "开启mariadb",
done

2022-03-01 02:50 UTC, fightdou commented on charts/openstack-dep/values.schema.json
> +                    "description": "MariaDB architecture. Allowed values: `standalone` or `replication`",
done

2022-03-01 02:50 UTC, fightdou commented on charts/openstack-dep/values.schema.json
> +		            "title": "自动生成密钥名称",
done

2022-03-01 02:50 UTC, fightdou commented on charts/openstack-dep/Chart.yaml
> +  - name: Openstack
done

2022-03-01 03:01 UTC, jeffyjf approved these changes

2022-03-01 03:01 UTC, merged