[common] add common charts
kungze/charts pull request #15
Opened 2022-03-10 01:34 UTC by fightdou

2022-03-10 10:14 UTC, jeffyjf requested changes

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/Chart.yaml
> +name: common
应该需要一个 type: library

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/README.md
> +# Openstack Kolla Helm Common Library Chart
library chart 应该不需要 README.md

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/templates/manifests/_job_cm_render.tpl
> +              value: {{ $envAll.Values.endpoints.oslo_db.database | quote }}
变量路径不要这么深，$envAll.Values.database.database

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/templates/manifests/_job_cm_render.tpl
> +              value: {{ $envAll.Values.endpoints.oslo_db.username | quote }}
$envAll.Values.database.userName

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/templates/manifests/_job_cm_render.tpl
> +            - name: MARIADB_URL
这个需要改一下了

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/templates/manifests/_job_cm_render.tpl
> +          defaultMode: 365
为什么 mode 是 365

2022-03-10 10:14 UTC, jeffyjf commented on charts/common/values.yaml
> +## bitnami/common
library chart 应该不需要 values.yaml

2022-03-10 14:33 UTC, fightdou commented on charts/common/README.md
> +# Openstack Kolla Helm Common Library Chart
没有README文件，生成readme得单元测试过不去

2022-03-10 14:35 UTC, fightdou commented on charts/common/README.md
> +# Openstack Kolla Helm Common Library Chart
要不就改action文件，把common charts 跳过

2022-03-11 00:43 UTC, fightdou commented on charts/common/templates/manifests/_job_cm_render.tpl
> +          defaultMode: 365
365转为八进制是0555，应该不太对，应该是0644，统一这么写吧

2022-03-11 00:47 UTC, fightdou commented on charts/common/templates/manifests/_job_cm_render.tpl
> +              value: {{ $envAll.Values.endpoints.oslo_db.database | quote }}
done

2022-03-11 00:47 UTC, fightdou commented on charts/common/templates/manifests/_job_cm_render.tpl
> +              value: {{ $envAll.Values.endpoints.oslo_db.username | quote }}
done

2022-03-11 00:47 UTC, fightdou commented on charts/common/templates/manifests/_job_cm_render.tpl
> +            - name: MARIADB_URL
done

2022-03-13 07:47 UTC, jeffyjf approved these changes

2022-03-13 07:47 UTC, merged